### ISSUE TITLE
Error seen running script to upload dbProfile results to local schema

### ISSUE THREAD

**Issue by NACHC-CAD** [OHDSI/DbDiagnostics#11]
I'm getting the error shown below running “Upload dbProfile results to a local schema”:

db_profile_results$STRATUM_1 <- as.character(db_profile_results$STRATUM_1)
Error in `$<-.data.frame`(`*tmp*`, STRATUM_1, value = character(0)) : 
replacement has 0 rows, data has 3077

Changing the instances of STRATUM_X to stratumX seems to have fixed this. I also made some adjustments to how the file parameters are defined. 

More details are here (a script that worked for me is included there):
https://forums.ohdsi.org/t/error-seen-running-script-to-upload-dbprofile-results-to-local-schema/19575/1

**Comment by clairblacketer** [comment]
@NACHC-CAD thank you, I have seen this issue as well. I will dig in a see if I can figure out what is going on.
