### ISSUE TITLE
Documentation: What to use for resultsTableName for DbDiagnostics executeDbDiagnostics?

### ISSUE THREAD

**Issue by NACHC-CAD** [OHDSI/DbDiagnostics#12]
I'm running DbDiagnostics base on the instructions at https://ohdsi.github.io/DbDiagnostics/index.html and the guide for creating the dataDiagnosticsSettingList at https://ohdsi.github.io/DbDiagnostics/articles/DataDiagnosticsSettings.html.  For the "Run the executeDbDiagnostics" script, I'm not sure what to use for resultsTableName.  What table needs to be specified for this?

```
    dbDiagnosticResults <- DbDiagnostics::executeDbDiagnostics(
      connectionDetails = dbProfileConnectionDetails,
      resultsDatabaseSchema = "demo_cdm_ach_res",
      resultsTableName = "",
      outputFolder = outputFolder,
      dataDiagnosticsSettingsList = settingsList
    )
```

(Question posted to the forum here: https://forums.ohdsi.org/t/what-to-use-for-resultstablename-for-dbdiagnostics-executedbdiagnostics/19579)

**Comment by clairblacketer** [comment]
Hi @NACHC-CAD that `resultsTableName` should be the table where you uploaded your dbProfile results.
