### ISSUE TITLE
Error in DbDiagnostics::executeDbProfile: unused argument overwriteAchilles 

### ISSUE THREAD

**Issue by ablack3** [OHDSI/DbDiagnostics#5]
The function `executeDbProfile` function signature in the documentation does not match the current release function signature. It looks like the overwriteAchilles option has been removed but the vignette has not been updated yet.

<img width="748" alt="image" src="https://user-images.githubusercontent.com/10227522/229883376-7c266641-18f8-4ab2-8c6e-8bac7a030e20.png">

https://github.com/OHDSI/DbDiagnostics/blob/cf7fcda85896678ff7f96733b525d4421552e585/vignettes/RunAndUploadDbProfile.Rmd#L67

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/10227522/229883848-bc5a59ee-f981-4415-9bbe-7e0cc297dc9f.png">

https://github.com/OHDSI/DbDiagnostics/blob/cf7fcda85896678ff7f96733b525d4421552e585/R/executeDbProfile.R#L54

**Comment by clairblacketer** [comment]
Thanks @ablack3! This was fixed with this commit: 

https://github.com/OHDSI/DbDiagnostics/commit/05bb08ffe3960b540d53ad9de8e3363b6dc48e56#diff-96516bad755f4dd8ce640b56ef58bb129d7299d93094713e0daabbba4316da69
