### ISSUE TITLE
Default for study end date uses analysis_id for 'observation period start month'

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/DbDiagnostics#9]
The following part of `executeDiagnostics` uses analysis_id 111 ('Number of persons by observation period start month') to determine the max study end date it can use. I think it should use analysis_id 112 ('Number of persons by observation period end month').
https://github.com/OHDSI/DbDiagnostics/blob/522ae9429b12fab4202f559b9de083efecb90bc1/R/executeDbDiagnostics.R#L175-L182

**Comment by clairblacketer** [comment]
@MaximMoinat this makes sense to me. This may also identify potential data quality issues related to the observation period
